name: Build and push the latest build to staging

on:  
  push:
    branches: [ "main" ]

jobs:  
  build_push_image:    
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login        
        uses: docker/login-action@v2.0.0
        with:          
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}
          
      - name: Build and push staging image          
        uses: docker/build-push-action@v3.1.0
        with:
          context: .
          tags: ${{secrets.ACR_NAME}}/contoso-website:latest
          push: true
          
  deploy:
    runs-on: ubuntu-20.04
    needs: build_push_image # Will wait for the execution of the previous job
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Helm tool installer
        uses: Azure/setup-helm@v3
        with:          
          version: v3.3.1      
           
          
      - name: Get AKS Credentials
        uses: Azure/k8s-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: mslearn-gh-pipelines-16993
          cluster-name: contoso-video
          
          
      - name: Run Helm Deploy
        run: |
          helm upgrade \
            --install \
            --create-namespace \
            --atomic \
            --wait \
            --namespace staging \
            contoso-website \
            ./kubernetes/contoso-website \
            --set image.repository=${{ secrets.ACR_NAME }} \
            --set dns.name=${{ secrets.DNS_NAME }}
